### ISSUE TITLE
syncronized blocks how to do

### ISSUE THREAD

**Issue by publicocean0** [lucav76/Fibry#14]
hi i have a question : 
Suppose i use a complex application ising many libraries ad suppose i call a function inside a fiber callback where there is a syncronized block (this function is inside a external dependecy). 
My question is 
in this case syncronized block coud be a bottleneck using fibers because it uses continualy mutual lock when is not necessary. In addition if i use many fibers in a unique resources i have to add locks for fibers . It is correct?

**Comment by lucav76** [comment]
Hi,
I apologize for the delay, as I noticed your question just now.

For the first case, if you access a method that is synchronized, the fiber will block. The documentation of Loom says that at this stage they do not yield if the body of the continuation holds a native lock (e.g. synchronized blocks), but they haven't decided yet if they will support it in the future.
It might require some experiments. If it does not yield, then you should be careful as I assume that if may fibers do, performance will suffer as the backing threads will block.

In the second case, if you use fibers as threads, yes, you need to synchronize in the resource. If you use actors, then you just need an actor to take care of your resource, and you will not need any synchronization as the actor will take care of serializing the access to the resource. If this is better than having threads in competition for a lock, might depend on the usage pattern and what the code does.
