### ISSUE TITLE
Fibers strategy doesn't work for embeddedHttpServer

### ISSUE THREAD

**Issue by hrj** [lucav76/Fibry#16]
The simple http server code given in the example:

```
Stereotypes.def.embeddedHttpServer(8080, new Stereotypes.HttpStringWorker("/", ex -> "Hello world!"));
```

works, but if I change `def` to `fibers`, it doesn't work. The client connects, but no response is received from the server.

Tested on latest loom EA build: `16-loom+4-56`

**Comment by lucav76** [comment]
Hi,
Thank you for submitting the bug. I am sorry for the late response, I just noticed now. I will check what's happening.

**Comment by lucav76** [comment]
Loom si experimental, and as such its API is not stable. It changes significantly. I will update Fibry to support the new version of Loom

**Comment by lucav76** [comment]
Now the version on GitHub should work.
As soon as I can I will publish version 2.2 on Maven Central. Thank you again for submitting the bug.

**Comment by hrj** [comment]
Thanks for the fix! Will try it out later.

Just another request: can you please create a release on Github whenever a new version is tagged? Those who are "watching for releases" will get a notification automatically from Github.

**Comment by lucav76** [comment]
Ok, that's a good idea. I will try to do that.

**Comment by lucav76** [comment]
But I am a  bit confused. Fibry has releases in GitHub, not only tags.  Isn't that enough?
I use the research-gate plugin to release.

**Comment by hrj** [comment]
I didn't get a notification for the 2.2 release although I am subscribed. Not sure why. Perhaps it was a one-off failure.

**Comment by hrj** [comment]
Just checked again. The side bar for the repository only says "14 tags". I think you need to create a release from Github interface for notifications to work.

**Comment by lucav76** [comment]
I can see them under Releases, but they don't seem releases. I will investigate.
Thanks!
