### ISSUE TITLE
any detail documents or wiki?

### ISSUE THREAD

**Issue by JintaoXIAO** [lucav76/Fibry#18]
thanks for your work!
I want to learn this code deeply, do you have any more detailed documents, or what should I read to learn the actor concurrency model? 
hope your replay, thanks

(sorry for my poor English:) )

**Comment by lucav76** [comment]
Hi Jintao,
Thank you for your words. I do not really have more documents.
To understand the principles, you can read about the actors model and you can quickly check Erlang, which was my inspiration for some constructs. If you haven't seen ir, you can also check my article on DZone:
https://dzone.com/articles/a-new-java-with-a-stronger-fiber

To learn how to use it, the best is to check the readme of course, and the examples. If there are things that are not clear or if you find some bugs, please feel free to contact me. I might also restructure the documentation next year.

Of course, feel free to ask me about the internals as well.
