### ISSUE TITLE
how to run distributed examples?

### ISSUE THREAD

**Issue by jun37213721** [lucav76/Fibry#23]
There are Alice and Bob class in examples/distributed/，how to run it？
It seems that Alice and Bob main() function will not run enter loop, it will exit immediately.
Thank you. @lucav76

**Comment by jun37213721** [comment]
And how to run Bob example?
It will throw exception when run in line: ch.ensureConnection()
java.net.ConnectException: Connection refused: connect
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:579)
	at java.base/sun.nio.ch.Net.connect(Net.java:586)
	at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:880)
	at java.base/java.nio.channels.SocketChannel.open(SocketChannel.java:285)
	at eu.lucaventuri.fibry.distributed.TcpChannel.getChannel(TcpChannel.java:86)
	at eu.lucaventuri.fibry.distributed.TcpChannel.ensureConnection(TcpChannel.java:111)
	at eu.lucaventuri.examples.distributed.Bob.main(Bob.java:29)

I think I should listen the port 9802, but how to do that?
Thank you.

**Comment by lucav76** [comment]
Hi,
Try to run the example in this order:
* MapActor
* ProxyA
* ProxyB
* Bob
* Alice

You should see:
"Bob answer: Bob received: Call from Alice"

I should probably write some more documentation about this parts...

**Comment by jun37213721** [comment]
Hi,
Thank you for your answer.

I try to run in order as you said in IntelliJ IDEA, 
- MapActor: ok
- ProxyA: It will exit immediately, output like:
> 9:19:13: Executing ':ProxyA.main()'...

> Connected to the target VM, address: 'localhost:7442', transport: 'socket'
> Task :compileJava UP-TO-DATE
> Task :processResources NO-SOURCE
> Task :classes UP-TO-DATE
> Disconnected from the target VM, address: 'localhost:7442', transport: 'socket'

> Task :ProxyA.main()
> *** proxyA listening on port 9801

> Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

> You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

> See https://docs.gradle.org/7.4/userguide/command_line_interface.html#sec:command_line_warnings

> BUILD SUCCESSFUL in 902ms
> 2 actionable tasks: 1 executed, 1 up-to-date
> 9:19:14: Execution finished ':ProxyA.main()'.

- ProxyB: output as ProxyA

I think it has not run in event loop, my code is branch master.
Thank you. @lucav76

**Comment by lucav76** [comment]
Hi,
This code hasn't change in a long time, so your version should be fine.

These are all the outputs that I see:
*** Map Actor UP
*** Map listening on port 9810 - HTTP on 9811

*** proxyA listening on port 9801

*** proxyB listening on port 9802

***** Bob UP

***** Alice UP
Bob answer: Bob received: Call from Alice

**Comment by lucav76** [comment]
As you see "*** proxyA listening on port 9801", it shoudl work. It should not exit because there are threads running. 

You could try adding a Thread.sleep(3_600_000) at the end of the main, just to be sure that it does not end, but it is weird.

**Comment by jun37213721** [comment]
Hi,
I think I has found the problem.
It will exit immediately in java 19,
and it will run coreect in java 11.
I'm guessing it has something about java 19 virtual thread.

And adding a Thread.sleep(3_600_000) in java 19 is also ok.

**Comment by lucav76** [comment]
Interesting! Thank you for the tip. I will try and fix it.
