### ISSUE TITLE
"no plans to make a distributed version of Fibry"

### ISSUE THREAD

**Issue by paul-hammant** [lucav76/Fibry#4]
Did you mean "no plans to make a binary (jar) distribution version of Fibry"

**Comment by lucav76** [comment]
No, Fibry is available on Maven central. I notice yesterday that I don't release jars, but I will try to fix that.

With "distributed" I mean that ideally actors should be able to run on remote servers, without the caller needing to know that. 
I actually plan to implement something simple that solve some problems. For example, I could send some statistics to an actor, and that could actually end up in another server that actually saves the data on a db.

**Comment by paul-hammant** [comment]
Thanks for clarification :)
